language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

script:
  - "npm run lint"
  - "npm run tslint"
  - "npm run build"

after_success:
  - test $TRAVIS_BRANCH = "master" &&
    npm run github-releases
