language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

script:
  - "npm run lint"
  - "npm run tslint"
  - "npm run build"

deploy:
  provider: script
  script: "npm run deploy"
  skip_cleanup: true
  on:
    tags: true
    branch: master
